[Application]
Name=EZProtocol
IniVersion=1.10

[Parameters]
Language=Portuguese
# Language=English
EZUI=Installer
# EZUI=Manufacturer
# EZUI=EZTechDev
CSVName=Aprovado.csv
CSVPath=\EZForecourt
SerialININame=EZSerial.ini
SerialINIPath=\EZForecourt


